### ISSUE TITLE
Excuse me!!!

### ISSUE THREAD

**Issue by ritchen** [RwChen/Test#1]
Hello, my user name is 'rw-chen', but I want to use 'rwchen' as my user name, but 'rwchen' has been occupied by your account, because I found that you do not often use the github account of 'rwchen', could you please ask you to change your user name to something else? If there is any other need, Please contact me at rw-chen@foxmai.com

**Comment by RwChen** [comment]
邮件已收到，thx~~~

**Comment by Rw-chen** [comment]
卧槽，你也是中国好兄嘚，所以能把用户名让给我吗 :see_no_evil: ，谢谢谢谢谢
